"""enrollment_request + lesson content_md

Revision ID: 0292b8d10bc4
Revises: 6403f9294955
Create Date: 2026-04-27 23:34:52.906355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0292b8d10bc4'
down_revision: Union[str, None] = '6403f9294955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_request',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='enrollment_request_status'), nullable=False),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('processed_by', sa.Uuid(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['study_group.id'], name=op.f('fk_enrollment_request_group_id_study_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by'], ['user.id'], name=op.f('fk_enrollment_request_processed_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_enrollment_request_student_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollment_request')),
    sa.UniqueConstraint('student_id', 'group_id', 'status', name='uq_enrollment_request_student_group_status')
    )
    op.create_index(op.f('ix_enrollment_request_group_id'), 'enrollment_request', ['group_id'], unique=False)
    op.create_index(op.f('ix_enrollment_request_student_id'), 'enrollment_request', ['student_id'], unique=False)
    op.add_column('lesson_instance', sa.Column('content_md', sa.String(length=20000), nullable=True))
    op.add_column('lesson_instance', sa.Column('summary', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_instance', 'summary')
    op.drop_column('lesson_instance', 'content_md')
    op.drop_index(op.f('ix_enrollment_request_student_id'), table_name='enrollment_request')
    op.drop_index(op.f('ix_enrollment_request_group_id'), table_name='enrollment_request')
    op.drop_table('enrollment_request')
    # ### end Alembic commands ###
