"""add learning + billing + notifications + audit + schedule

Revision ID: 4e2b09373ffc
Revises: d04c4b1a411b
Create Date: 2026-04-27 22:04:50.004939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4e2b09373ffc'
down_revision: Union[str, None] = 'd04c4b1a411b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], name=op.f('fk_audit_log_actor_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_table('notification_outbox',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'telegram', 'sms', 'push', 'in_app', name='notification_channel'), nullable=False),
    sa.Column('template_code', sa.String(length=80), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.String(length=8000), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sending', 'delivered', 'failed', name='notification_status'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_outbox_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_outbox'))
    )
    op.create_index(op.f('ix_notification_outbox_user_id'), 'notification_outbox', ['user_id'], unique=False)
    op.create_table('pricing_plan',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.Enum('per_lesson', 'package', 'subscription', name='pricing_plan_kind'), nullable=False),
    sa.Column('lessons_included', sa.Integer(), nullable=False),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], name=op.f('fk_pricing_plan_branch_id_branch'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_plan'))
    )
    op.create_table('schedule_slot',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['study_group.id'], name=op.f('fk_schedule_slot_group_id_study_group'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_slot'))
    )
    op.create_index(op.f('ix_schedule_slot_group_id'), 'schedule_slot', ['group_id'], unique=False)
    op.create_table('subscription',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('pricing_plan_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lessons_remaining', sa.Integer(), nullable=False),
    sa.Column('frozen_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('frozen_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'expired', 'refunded', name='subscription_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pricing_plan_id'], ['pricing_plan.id'], name=op.f('fk_subscription_pricing_plan_id_pricing_plan'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_subscription_student_id_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription'))
    )
    op.create_index(op.f('ix_subscription_student_id'), 'subscription', ['student_id'], unique=False)
    op.create_table('assignment',
    sa.Column('lesson_instance_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('quiz', 'writing', 'speaking', 'reading', name='assignment_kind'), nullable=False),
    sa.Column('instructions', sa.String(length=4000), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('auto_check', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_instance_id'], ['lesson_instance.id'], name=op.f('fk_assignment_lesson_instance_id_lesson_instance'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignment'))
    )
    op.create_index(op.f('ix_assignment_lesson_instance_id'), 'assignment', ['lesson_instance_id'], unique=False)
    op.create_table('payment',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_ref', sa.String(length=100), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'refunded', name='payment_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_payment_student_id_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], name=op.f('fk_payment_subscription_id_subscription'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment')),
    sa.UniqueConstraint('idempotency_key', name='uq_payment_idempotency_key')
    )
    op.create_index(op.f('ix_payment_student_id'), 'payment', ['student_id'], unique=False)
    op.create_table('lesson_credit_ledger',
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_instance_id', sa.Uuid(), nullable=True),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('purchase', 'lesson_debit', 'freeze_refund', 'cancellation_refund', 'bonus', 'correction', name='ledger_reason'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_lesson_credit_ledger_created_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_instance_id'], ['lesson_instance.id'], name=op.f('fk_lesson_credit_ledger_lesson_instance_id_lesson_instance'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name=op.f('fk_lesson_credit_ledger_payment_id_payment'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], name=op.f('fk_lesson_credit_ledger_subscription_id_subscription'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_credit_ledger'))
    )
    op.create_index(op.f('ix_lesson_credit_ledger_subscription_id'), 'lesson_credit_ledger', ['subscription_id'], unique=False)
    op.create_table('submission',
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'graded', 'returned', name='submission_status'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.String(length=4000), nullable=True),
    sa.Column('rubric', sa.JSON(), nullable=True),
    sa.Column('graded_by', sa.Uuid(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], name=op.f('fk_submission_assignment_id_assignment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graded_by'], ['user.id'], name=op.f('fk_submission_graded_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_submission_student_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission'))
    )
    op.create_index(op.f('ix_submission_assignment_id'), 'submission', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_submission_student_id'), 'submission', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_student_id'), table_name='submission')
    op.drop_index(op.f('ix_submission_assignment_id'), table_name='submission')
    op.drop_table('submission')
    op.drop_index(op.f('ix_lesson_credit_ledger_subscription_id'), table_name='lesson_credit_ledger')
    op.drop_table('lesson_credit_ledger')
    op.drop_index(op.f('ix_payment_student_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_assignment_lesson_instance_id'), table_name='assignment')
    op.drop_table('assignment')
    op.drop_index(op.f('ix_subscription_student_id'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_schedule_slot_group_id'), table_name='schedule_slot')
    op.drop_table('schedule_slot')
    op.drop_table('pricing_plan')
    op.drop_index(op.f('ix_notification_outbox_user_id'), table_name='notification_outbox')
    op.drop_table('notification_outbox')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
