"""course_content: modules + features + reviews

Revision ID: 6403f9294955
Revises: 4e2b09373ffc
Create Date: 2026-04-27 23:03:50.680507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6403f9294955'
down_revision: Union[str, None] = '4e2b09373ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_feature',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_course_feature_course_id_course'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_feature'))
    )
    op.create_index(op.f('ix_course_feature_course_id'), 'course_feature', ['course_id'], unique=False)
    op.create_table('course_module',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=2000), nullable=True),
    sa.Column('lessons_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_course_module_course_id_course'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_module')),
    sa.UniqueConstraint('course_id', 'order_index', name='uq_course_module_order')
    )
    op.create_index(op.f('ix_course_module_course_id'), 'course_module', ['course_id'], unique=False)
    op.create_table('course_review',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('author_name', sa.String(length=120), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], name=op.f('fk_course_review_author_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_course_review_course_id_course'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_review'))
    )
    op.create_index(op.f('ix_course_review_course_id'), 'course_review', ['course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_review_course_id'), table_name='course_review')
    op.drop_table('course_review')
    op.drop_index(op.f('ix_course_module_course_id'), table_name='course_module')
    op.drop_table('course_module')
    op.drop_index(op.f('ix_course_feature_course_id'), table_name='course_feature')
    op.drop_table('course_feature')
    # ### end Alembic commands ###
