"""rooms + group.room_id

Revision ID: 8168ad2a0225
Revises: 0292b8d10bc4
Create Date: 2026-04-28 14:41:43.009240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8168ad2a0225'
down_revision: Union[str, None] = '0292b8d10bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('equipment', sa.String(length=500), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], name=op.f('fk_room_branch_id_branch'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room')),
    sa.UniqueConstraint('branch_id', 'name', name='uq_room_branch_name')
    )
    op.create_index(op.f('ix_room_branch_id'), 'room', ['branch_id'], unique=False)
    op.add_column('study_group', sa.Column('room_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_study_group_room_id_room'), 'study_group', 'room', ['room_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_study_group_room_id_room'), 'study_group', type_='foreignkey')
    op.drop_column('study_group', 'room_id')
    op.drop_index(op.f('ix_room_branch_id'), table_name='room')
    op.drop_table('room')
    # ### end Alembic commands ###
