"""initial schema

Revision ID: d04c4b1a411b
Revises: 
Create Date: 2026-04-27 21:54:40.258166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd04c4b1a411b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('language', sa.Enum('en', 'de', 'fr', 'it', 'es', 'zh', 'ja', 'ko', name='course_language'), nullable=False),
    sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='course_cefr_level'), nullable=False),
    sa.Column('age_group', sa.Enum('kids', 'teens', 'adults', name='course_age_group'), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('lessons_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('methodology', sa.String(length=50), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course'))
    )
    op.create_index(op.f('ix_course_age_group'), 'course', ['age_group'], unique=False)
    op.create_index(op.f('ix_course_language'), 'course', ['language'], unique=False)
    op.create_index(op.f('ix_course_level'), 'course', ['level'], unique=False)
    op.create_table('user',
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_table('branch',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('manager_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manager_user_id'], ['user.id'], name=op.f('fk_branch_manager_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branch'))
    )
    op.create_index(op.f('ix_branch_city'), 'branch', ['city'], unique=False)
    op.create_table('parent_link',
    sa.Column('parent_user_id', sa.Uuid(), nullable=False),
    sa.Column('student_user_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=False),
    sa.Column('consent_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_user_id'], ['user.id'], name=op.f('fk_parent_link_parent_user_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_user_id'], ['user.id'], name=op.f('fk_parent_link_student_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parent_link')),
    sa.UniqueConstraint('parent_user_id', 'student_user_id', name='uq_parent_student')
    )
    op.create_index(op.f('ix_parent_link_parent_user_id'), 'parent_link', ['parent_user_id'], unique=False)
    op.create_index(op.f('ix_parent_link_student_user_id'), 'parent_link', ['student_user_id'], unique=False)
    op.create_table('student_profile',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('cefr_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level_kind'), nullable=True),
    sa.Column('target_exam', sa.String(length=50), nullable=True),
    sa.Column('learning_goals', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_student_profile_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_student_profile'))
    )
    op.create_table('teacher_profile',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bio', sa.String(length=4000), nullable=True),
    sa.Column('cambridge_cert', sa.String(length=50), nullable=True),
    sa.Column('hourly_rate_minor', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_teacher_profile_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_teacher_profile'))
    )
    op.create_table('study_group',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('teacher_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.Enum('offline', 'online', 'hybrid', name='group_mode'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'active', 'finished', 'cancelled', name='group_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], name=op.f('fk_study_group_branch_id_branch'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_study_group_course_id_course'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], name=op.f('fk_study_group_teacher_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_group'))
    )
    op.create_index(op.f('ix_study_group_branch_id'), 'study_group', ['branch_id'], unique=False)
    op.create_index(op.f('ix_study_group_course_id'), 'study_group', ['course_id'], unique=False)
    op.create_index(op.f('ix_study_group_teacher_id'), 'study_group', ['teacher_id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('student', 'teacher', 'parent', 'methodist', 'branch_manager', 'admin', 'b2b_coordinator', name='user_role_kind'), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], name=op.f('fk_user_role_branch_id_branch'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_role_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_role')),
    sa.UniqueConstraint('user_id', 'role', 'branch_id', name='uq_user_role_branch')
    )
    op.create_index(op.f('ix_user_role_branch_id'), 'user_role', ['branch_id'], unique=False)
    op.create_index(op.f('ix_user_role_user_id'), 'user_role', ['user_id'], unique=False)
    op.create_table('enrollment',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('placement_score', sa.Integer(), nullable=True),
    sa.Column('final_grade', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['study_group.id'], name=op.f('fk_enrollment_group_id_study_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_enrollment_student_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollment')),
    sa.UniqueConstraint('student_id', 'group_id', name='uq_enrollment_student_group')
    )
    op.create_index(op.f('ix_enrollment_group_id'), 'enrollment', ['group_id'], unique=False)
    op.create_index(op.f('ix_enrollment_student_id'), 'enrollment', ['student_id'], unique=False)
    op.create_table('lesson_instance',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('actual_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'finished', 'cancelled', name='lesson_status'), nullable=False),
    sa.Column('notes_for_methodist', sa.String(length=4000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['study_group.id'], name=op.f('fk_lesson_instance_group_id_study_group'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_instance'))
    )
    op.create_index(op.f('ix_lesson_instance_group_id'), 'lesson_instance', ['group_id'], unique=False)
    op.create_index(op.f('ix_lesson_instance_scheduled_at'), 'lesson_instance', ['scheduled_at'], unique=False)
    op.create_table('attendance',
    sa.Column('lesson_instance_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('present', 'late', 'absent', 'excused', name='attendance_status'), nullable=False),
    sa.Column('participation_score', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_instance_id'], ['lesson_instance.id'], name=op.f('fk_attendance_lesson_instance_id_lesson_instance'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['user.id'], name=op.f('fk_attendance_recorded_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_attendance_student_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_instance_id', 'student_id', name='pk_attendance')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.drop_index(op.f('ix_lesson_instance_scheduled_at'), table_name='lesson_instance')
    op.drop_index(op.f('ix_lesson_instance_group_id'), table_name='lesson_instance')
    op.drop_table('lesson_instance')
    op.drop_index(op.f('ix_enrollment_student_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_group_id'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index(op.f('ix_user_role_user_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_branch_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_study_group_teacher_id'), table_name='study_group')
    op.drop_index(op.f('ix_study_group_course_id'), table_name='study_group')
    op.drop_index(op.f('ix_study_group_branch_id'), table_name='study_group')
    op.drop_table('study_group')
    op.drop_table('teacher_profile')
    op.drop_table('student_profile')
    op.drop_index(op.f('ix_parent_link_student_user_id'), table_name='parent_link')
    op.drop_index(op.f('ix_parent_link_parent_user_id'), table_name='parent_link')
    op.drop_table('parent_link')
    op.drop_index(op.f('ix_branch_city'), table_name='branch')
    op.drop_table('branch')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_course_level'), table_name='course')
    op.drop_index(op.f('ix_course_language'), table_name='course')
    op.drop_index(op.f('ix_course_age_group'), table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###
